# Exploratory data analysis on OpenNeuro data

### Atif M. Mahmud

### Introduction

This data has been downloaded from https://openneuro.org/datasets/ds003838/versions/1.0.6

This excerpt is from the webpage:
> 
> This dataset consists of raw 64-channel EEG, cardiovascular (electrocardiography and photoplethysmography), and pupillometry data from 86 human participants during 4 minutes of eyes-closed resting and during performance of a
> classic working memory task – digit span task with serial recall. The participants either memorized (memory) or just listened to (control condition) sequences of 5, 9, or 13 digits presented auditorily with 2 second stimulus
> onset asynchrony. The dataset can be used for (1) developing algorithms for cognitive load discrimination and detection of cognitive overload; (2) studying neural (event-related potentials and brain oscillations) and
> peripheral physiological (electrocardiography, photoplethysmography, and pupillometry) signals during encoding and maintenance of each sequentially presented memory item in a fine time scale; (3) correlating cognitive load and > individual differences in working memory to neural and peripheral physiology, and studying the relationship between the physiological signals; (4) integration of the physiological findings with the vast knowledge coming from
> behavioral studies of verbal working memory in simple span paradigms.
> 
> EEG, pupillometry, ECG and photoplethysmography, and behavioral data are stored separately in corresponding folders. Each data record can consist of four data folders:  
> - beh - behavioral data: correctness of the recall in the memory trials
> - ecg - electrocardiography (ECG)
> - photoplethysmography (PPG) data
> - eeg - EEG data
> - pupil - pupillometry and eye-tracking data
> 
> Some of the participants had some physiological data missing: sub-017, sub-094 have no pupillometry data sub-017, sub-037, sub-066 have no ECG and PPG data sub-013, sub-014, sub-015, sub-016, sub-017, sub-018, sub-019,
> sub-020, sub-021, sub-022, sub-023, sub-024, sub-025, sub-026, sub-027, sub-028, sub-029, sub-030, sub-031, sub-037, sub-066 have no EEG data

In [1]:
import mne
import pandas as pd
import csv
import matplotlib.pyplot as plt
import warnings
import os
import numpy as np
from mne_icalabel import label_components
from IPython.display import display
import traceback

mne.set_log_level("ERROR")
warnings.filterwarnings("ignore", category=UserWarning, module="pymatreader")

c:\Users\atifm\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Our analysis

There are 86 participants. We won't use the following because they have missing data.  
- sub-013 to sub-031
- sub-037
- sub-066
- sub-094

In [5]:
# The EEG data is in the `_eeg.set` files
# %matplotlib qt

raw_sub40_task = mne.io.read_raw_eeglab("data/sub-040/eeg/sub-040_task-memory_eeg.set", preload=True)
print(f"The shape of the date is {raw_sub40_task.get_data().shape}")
print(f"The channel names are: {raw_sub40_task.ch_names}")

# raw_sub40_task.plot()
# plt.show()

The shape of the date is (63, 7176340)
The channel names are: ['Fp1', 'Fz', 'F3', 'F7', 'FT9', 'FC5', 'FC1', 'C3', 'T7', 'TP9', 'CP5', 'CP1', 'Pz', 'P3', 'P7', 'O1', 'Oz', 'O2', 'P4', 'P8', 'TP10', 'CP6', 'CP2', 'Cz', 'C4', 'T8', 'FT10', 'FC6', 'FC2', 'F4', 'F8', 'Fp2', 'AF7', 'AF3', 'AFz', 'F1', 'F5', 'FT7', 'FC3', 'C1', 'C5', 'TP7', 'CP3', 'P1', 'P5', 'PO7', 'PO3', 'POz', 'PO4', 'PO8', 'P6', 'P2', 'CPz', 'CP4', 'TP8', 'C6', 'C2', 'FC4', 'FT8', 'F6', 'AF8', 'AF4', 'F2']

From participant 40, we see that we are able to load the EEG data using `mne` and `pymatreader`. This is a 64-channel EEG, so we have 63-channels of data since one of the channels is a reference and the other values are recorded in reference to that.

## EEG Analysis

### Load, filter, and re-reference data

In [ ]:
participants = [32, 33, 34, 35, 36, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
print(f"N =  {len(participants)}")

cache_dir = "data/filtered-referenced-eeg"
os.makedirs(cache_dir, exist_ok=True)

for participant in participants:
    cached_file = f"{cache_dir}/sub-0{participant}-task-eeg_filtered-referenced.fif"

    if os.path.exists(cached_file):
        print("File exists!")
    else:
        # Cached, pre-processed file not found: load raw file
        file = f"data/sub-0{participant}/eeg/sub-0{participant}_task-memory_eeg.set"
        raw = mne.io.read_raw_eeglab(file, preload=True)

        # Frequency filter: High-pass 1Hz, Low-pass 45Hz & re-reference to averaged reference
        # Based on the original authors' implementation: (Kosachenko et al., 2023)
        raw.filter(l_freq=1, h_freq=45)
        raw.set_eeg_reference("average")

        # Save file to cache
        raw.save(cached_file, overwrite=True)

### Artifact removal with independent component analysis

In [ ]:
participant = 32
cache_dir = "data/filtered-referenced-eeg"
cached_file = f"{cache_dir}/sub-0{participant}-task-eeg_filtered-referenced.fif"

if os.path.exists(cached_file):
    print(f"Found file {cached_file}")
    raw = mne.io.read_raw_fif(cached_file, preload=True)
    ica = mne.preprocessing.ICA(n_components=0.99, method="fastica", random_state=42)
    ica.fit(raw)
    ica.plot_components()
    ica_labels = label_components(raw, ica, "iclabel")
    display(ica_labels)
else:
    print(f"File - {cached_file} not found!")

In [ ]:
display(pd.DataFrame(ica_labels))

#### For each participant remove the artifacts using mne-icalabel

In [ ]:
cache_dir = "data/filtered-referenced-eeg"
target_dir = "data/ica-excluded-eeg"
os.makedirs(target_dir, exist_ok=True)

participants = [32, 33, 34, 35, 36, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
for participant in participants:
    cached_file = f"{cache_dir}/sub-0{participant}-task-eeg_filtered-referenced.fif"
    target_file = f"{target_dir}/sub-0{participant}-task-eeg_ica-cleaned.fif"
    if os.path.exists(target_file):
        print(f"ICA cleaned file exists for {participant} - {target_file}. Skipping...")
        continue
    if os.path.exists(cached_file):
        try:
            print(f"Found file {cached_file}")
            raw = mne.io.read_raw_fif(cached_file, preload=True)
            ica = mne.preprocessing.ICA(n_components=0.99, method="fastica", random_state=42)
            ica.fit(raw)
            ica_labels = label_components(raw, ica, "iclabel")
            excluded_components = []
            for idx, label in enumerate(ica_labels["labels"]):
                if label != "brain":
                    excluded_components.append(idx)
                    print(f"Excluding index {idx} from {participant} because label is {label}")
            print(f"For participant {participant}, we are excluding components {excluded_components}")
            ica.exclude = excluded_components
            eeg_ica_cleaned = ica.apply(raw.copy())
            eeg_ica_cleaned.save(target_file, overwrite=True)
            print(f"@ Saved file {target_file}")
        except Exception as error:
            print(f"Error {error} while trying to apply ICA to participant {participant}")
    else:
        print(f"File - {cached_file} not found!")

#### Epoching the data and creating the X and Y for random forest

In [6]:
## LABEL = the event string like x500913
## CODE = a numeric code of the event

def parse_label(label):
    if not label.startswith(("5", "6")) or len(label) > 7 or len(label) < 6:
        print(f"Skipping this label: label {label} is invalid.")
        return None
    condition_flag = label[0]
    if condition_flag not in ("5", "6"):
        print(f"Error: label {label}. Condition flag is invalid")
    condition = "Memory" if condition_flag == "6" else "Listen"
    position = int(label[2:4])
    load = int(label[4:6])
    correct = None
    if condition == "Memory" and len(label) > 6:
        correct = "Correct" if label[6] == "1" else "Incorrect"
    return {"label" : label, "condition" : condition, "position" : position, "load" : load, "correct" : correct}


def compute_power(epochs):
    freq = np.concatenate([np.arange(8, 13, 2), np.arange(30, 45, 2)]) # Alpha and Gamma. We are using 45 because we cutoff after that in our filter. Sparser sampling.
    n_cycles = freq / 2
    powers = epochs.compute_tfr(method="morlet", freqs=freq, n_cycles=n_cycles, decim=4, average=False)
    powers.data = powers.data.astype(np.float32)
    # Compute power relative to a time window
    powers.apply_baseline(baseline=(-1.5, -0.2), mode="logratio")
    
    # Crop to get Alpha (8-12) and Gamma (30-44). Average across time, frequencies, channels
    # This will give me a single value for whole scalp
    # FUTURE TODO: average over regions to get ROI specific values
    alpha_mean = powers.copy().crop(fmin=8, fmax=12).data.mean(axis=(1, 2, 3))
    gamma_mean = powers.copy().crop(fmin=30, fmax=44).data.mean(axis=(1, 2, 3))

    return pd.DataFrame({"alpha_power" : alpha_mean, "gamma_power" : gamma_mean})


preprocessed_eeg_dir = "data/ica-excluded-eeg"
def process_participant_data(num):
    print(f"Processing epoch for participant {num}")
    eeg_file = f"{preprocessed_eeg_dir}/sub-0{num}-task-eeg_ica-cleaned.fif"
    if not os.path.exists(eeg_file):
        print(f"File {eeg_file} not found")
    else:
        raw = mne.io.read_raw_fif(eeg_file, preload=True)
        print(f"Read file {eeg_file}")
        events, event_id = mne.events_from_annotations(raw)
        code_to_label = {v : k for k, v in event_id.items()} # Reverse map. Get a dict where event "code" is KEY and "label" is VALUE

    # Loop through events in time series
    metadata, valid_event_indices = [], []
    for index, event in enumerate(events):
        event_description = parse_label(code_to_label[event[2]]) # Get the label from the event code which is in the 3rd position in "event"
        if event_description:
            metadata.append(event_description)
            valid_event_indices.append(index)
    
    metadata_df = pd.DataFrame(metadata) # Create metadata dataframe
    valid_events = events[valid_event_indices] # Get the list of clean event codes
    matched_event_labels = {k: v for k, v in event_id.items() if parse_label(k)} # Get the dictionary of event labels to codes, but only where it's valid label

    # Create epoch object: from 1.5 before to 3.5 as authors did
    epochs = mne.Epochs(raw, events=valid_events, event_id=matched_event_labels, tmin=-1.5, tmax=3.5, metadata=metadata_df)

    print(f"Start computing power for participant {num}")
    powers = compute_power(epochs)
    participant_df = epochs.metadata.reset_index(drop=True).copy()
    participant_df["alpha_power"] = powers["alpha_power"].values
    participant_df["gamma_power"] = powers["gamma_power"].values
    participant_df["participant"] = num
    print(f"\nBelow is dataframe for participant {num}")
    display(participant_df)
    return participant_df

participants_batch_1 = [32, 33, 34, 35, 36, 38, 39, 40, 41, 42]
participants_batch_2 = [43, 44, 45, 46, 47, 48, 49, 50, 51, 52]
participants_batch_3 = [53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65] # We will leave this out for lack of time

all_participants = []

print(f"Starting batch_1. all_participants shape: {len(all_participants)}")
for participant in participants_batch_1:
    print(f"\n\nProcessing epoch and power for participant {participant}")
    # try:
    all_participants.append(process_participant_data(participant))
    # except Exception as error:
    #    print(f"Skipped participant {participant}. Error {error}.")

print(f"Starting batch_2. all_participants shape: {len(all_participants)}")
for participant in participants_batch_2:
    print(f"\nProcessing epoch and power for participant {participant}")
    try:
        all_participants.append(process_participant_data(participant))
    except Exception as error:
        print(f"Skipped participant {participant}. Error {error}.")

all_participants_df = pd.concat(all_participants, ignore_index=True)
display(all_particpants)

Starting batch_1. all_participants shape: 0


Processing epoch and power for participant 32
Processing epoch for participant 32
Read file data/ica-excluded-eeg/sub-032-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 32

Below is dataframe for participant 32

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500113,Listen,1,13,NaN,-0.057477,-0.192534,32
1,500213,Listen,2,13,NaN,-0.394398,-0.184071,32
2,500313,Listen,3,13,NaN,-0.412928,-0.205873,32
3,500413,Listen,4,13,NaN,-0.067001,-0.229368,32
4,500513,Listen,5,13,NaN,-0.253803,-0.232337,32
...,...,...,...,...,...,...,...,...
1453,500509,Listen,5,9,NaN,-0.036467,-0.180683,32
1454,500609,Listen,6,9,NaN,-0.180830,-0.229368,32
1455,500709,Listen,7,9,NaN,-0.352032,-0.221582,32
1456,500809,Listen,8,9,NaN,-0.604756,-0.264687,32
1457,500909,Listen,9,9,NaN,-0.057744,-0.237288,32

Processing epoch and power for participant 33
Processing epoch for participant 33
Read file data/ica-excluded-eeg/sub-033-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 33

Below is dataframe for participant 33

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.242723,-0.222707,33
1,500205,Listen,2,5,NaN,-0.124337,-0.274919,33
2,500305,Listen,3,5,NaN,-0.301087,-0.223233,33
3,500405,Listen,4,5,NaN,-0.115559,-0.210234,33
4,500505,Listen,5,5,NaN,-0.346275,-0.184535,33
...,...,...,...,...,...,...,...,...
1453,500913,Listen,9,13,NaN,-0.090464,-0.170582,33
1454,501013,Listen,10,13,NaN,-0.373699,-0.200998,33
1455,501113,Listen,11,13,NaN,-0.336047,-0.321981,33
1456,501213,Listen,12,13,NaN,-0.113180,-0.137317,33
1457,501313,Listen,13,13,NaN,-0.044272,-0.239809,33

Processing epoch and power for participant 34
Processing epoch for participant 34
Read file data/ica-excluded-eeg/sub-034-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 34

Below is dataframe for participant 34

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500109,Listen,1,9,NaN,-0.128890,-0.221936,34
1,500209,Listen,2,9,NaN,-0.204152,-0.173759,34
2,500309,Listen,3,9,NaN,-0.211416,-0.282749,34
3,500409,Listen,4,9,NaN,-0.161732,-0.270403,34
4,500509,Listen,5,9,NaN,-0.199526,-0.216278,34
...,...,...,...,...,...,...,...,...
1453,500105,Listen,1,5,NaN,-0.270378,-0.261384,34
1454,500205,Listen,2,5,NaN,-0.067704,-0.235512,34
1455,500305,Listen,3,5,NaN,-0.503443,-0.231629,34
1456,500405,Listen,4,5,NaN,-0.066742,-0.219219,34
1457,500505,Listen,5,5,NaN,-0.143067,-0.218548,34

Processing epoch and power for participant 35
Processing epoch for participant 35
Read file data/ica-excluded-eeg/sub-035-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 35

Below is dataframe for participant 35

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500109,Listen,1,9,NaN,-0.072878,0.167234,35
1,500209,Listen,2,9,NaN,-0.206377,-0.708037,35
2,500309,Listen,3,9,NaN,0.042544,-0.423881,35
3,500409,Listen,4,9,NaN,-0.220384,-0.280093,35
4,500509,Listen,5,9,NaN,-0.602325,-0.261311,35
...,...,...,...,...,...,...,...,...
1453,500105,Listen,1,5,NaN,-0.383378,-0.979107,35
1454,500205,Listen,2,5,NaN,-0.110037,-0.221911,35
1455,500305,Listen,3,5,NaN,0.061156,-0.255064,35
1456,500405,Listen,4,5,NaN,-0.330573,-0.271206,35
1457,500505,Listen,5,5,NaN,-0.501967,-0.217448,35

Processing epoch and power for participant 36
Processing epoch for participant 36
Read file data/ica-excluded-eeg/sub-036-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 36

Below is dataframe for participant 36

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500109,Listen,1,9,NaN,-0.180928,-0.187683,36
1,500209,Listen,2,9,NaN,-0.671721,-0.248103,36
2,500309,Listen,3,9,NaN,-0.211208,-0.158283,36
3,500409,Listen,4,9,NaN,-0.029740,-0.240133,36
4,500509,Listen,5,9,NaN,-0.478887,-0.157690,36
...,...,...,...,...,...,...,...,...
1453,500913,Listen,9,13,NaN,-0.143738,-0.203890,36
1454,501013,Listen,10,13,NaN,-0.133918,-0.214304,36
1455,501113,Listen,11,13,NaN,-0.341903,-0.251264,36
1456,501213,Listen,12,13,NaN,-0.374983,-0.189009,36
1457,501313,Listen,13,13,NaN,0.033954,-0.163954,36

Processing epoch and power for participant 38
Processing epoch for participant 38
Read file data/ica-excluded-eeg/sub-038-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 38

Below is dataframe for participant 38

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500109,Listen,1,9,NaN,-0.284264,-0.255115,38
1,500209,Listen,2,9,NaN,-0.292709,-0.291010,38
2,500309,Listen,3,9,NaN,-0.193070,-0.172688,38
3,500409,Listen,4,9,NaN,-0.360311,-0.235364,38
4,500509,Listen,5,9,NaN,-0.113748,-0.172219,38
...,...,...,...,...,...,...,...,...
1453,500509,Listen,5,9,NaN,-0.250372,-0.180606,38
1454,500609,Listen,6,9,NaN,-0.278825,-0.263134,38
1455,500709,Listen,7,9,NaN,-0.004958,-0.155220,38
1456,500809,Listen,8,9,NaN,-0.368673,-0.186861,38
1457,500909,Listen,9,9,NaN,-0.111906,-0.205041,38

Processing epoch and power for participant 39
Processing epoch for participant 39
Read file data/ica-excluded-eeg/sub-039-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 39

Below is dataframe for participant 39

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500113,Listen,1,13,NaN,-0.251149,-0.081201,39
1,500213,Listen,2,13,NaN,-0.153386,-0.207852,39
2,500313,Listen,3,13,NaN,-0.266052,-0.186411,39
3,500413,Listen,4,13,NaN,-0.293975,-0.191721,39
4,500513,Listen,5,13,NaN,-0.168192,-0.205608,39
...,...,...,...,...,...,...,...,...
1453,500913,Listen,9,13,NaN,-0.071554,-0.075699,39
1454,501013,Listen,10,13,NaN,-0.278032,-0.209728,39
1455,501113,Listen,11,13,NaN,-0.215518,-0.216861,39
1456,501213,Listen,12,13,NaN,-0.241589,-0.302485,39
1457,501313,Listen,13,13,NaN,-0.020681,-0.299722,39

Processing epoch and power for participant 40
Processing epoch for participant 40
Read file data/ica-excluded-eeg/sub-040-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 40

Below is dataframe for participant 40

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.387590,-0.178081,40
1,500205,Listen,2,5,NaN,-0.093161,-0.253807,40
2,500305,Listen,3,5,NaN,-0.739557,-0.238878,40
3,500405,Listen,4,5,NaN,-0.409928,-0.231946,40
4,500505,Listen,5,5,NaN,0.121877,-0.261157,40
...,...,...,...,...,...,...,...,...
1453,500509,Listen,5,9,NaN,-0.237558,-0.155675,40
1454,500609,Listen,6,9,NaN,-0.295699,-0.165147,40
1455,500709,Listen,7,9,NaN,-0.185174,-0.259072,40
1456,500809,Listen,8,9,NaN,-0.190307,-0.257805,40
1457,500909,Listen,9,9,NaN,-0.076972,-0.242566,40

Processing epoch and power for participant 41
Processing epoch for participant 41
Read file data/ica-excluded-eeg/sub-041-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 41

Below is dataframe for participant 41

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500113,Listen,1,13,NaN,-0.219654,-0.185846,41
1,500213,Listen,2,13,NaN,-0.303136,-0.370274,41
2,500313,Listen,3,13,NaN,-0.130941,-0.235445,41
3,500413,Listen,4,13,NaN,-0.189075,-0.228177,41
4,500513,Listen,5,13,NaN,-0.471542,-0.291323,41
...,...,...,...,...,...,...,...,...
1453,500913,Listen,9,13,NaN,-0.239886,-0.192770,41
1454,501013,Listen,10,13,NaN,-0.382225,-0.218583,41
1455,501113,Listen,11,13,NaN,-0.649968,-0.190628,41
1456,501213,Listen,12,13,NaN,-0.318815,-0.189410,41
1457,501313,Listen,13,13,NaN,-0.345053,-0.210099,41

Processing epoch and power for participant 42
Processing epoch for participant 42
Read file data/ica-excluded-eeg/sub-042-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 42

Below is dataframe for participant 42

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.104320,-0.220051,42
1,500205,Listen,2,5,NaN,-0.123044,-0.213357,42
2,500305,Listen,3,5,NaN,-0.363176,-0.277111,42
3,500405,Listen,4,5,NaN,-0.128775,-0.257385,42
4,500505,Listen,5,5,NaN,-0.003193,-0.097499,42
...,...,...,...,...,...,...,...,...
1480,500913,Listen,9,13,NaN,-0.253129,-0.226396,42
1481,501013,Listen,10,13,NaN,-0.473263,-0.176171,42
1482,501113,Listen,11,13,NaN,-0.361530,-0.285105,42
1483,501213,Listen,12,13,NaN,0.079406,-0.129561,42
1484,501313,Listen,13,13,NaN,-0.084644,-0.192351,42

Starting batch_2. all_participants shape: 10

Processing epoch and power for participant 43
Processing epoch for participant 43
Read file data/ica-excluded-eeg/sub-043-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 43

Below is dataframe for participant 43

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.451743,-0.264343,43
1,500205,Listen,2,5,NaN,-0.247467,-0.211393,43
2,500305,Listen,3,5,NaN,-0.405957,-0.204277,43
3,500405,Listen,4,5,NaN,-0.004535,-0.242824,43
4,500505,Listen,5,5,NaN,-0.312642,-0.245429,43
...,...,...,...,...,...,...,...,...
1453,500105,Listen,1,5,NaN,-0.239190,0.078830,43
1454,500205,Listen,2,5,NaN,-0.324585,-0.667859,43
1455,500305,Listen,3,5,NaN,0.303984,-0.273656,43
1456,500405,Listen,4,5,NaN,0.007399,-0.269695,43
1457,500505,Listen,5,5,NaN,-0.486308,-0.273209,43

Processing epoch and power for participant 44
Processing epoch for participant 44
Read file data/ica-excluded-eeg/sub-044-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 44

Below is dataframe for participant 44

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.163811,-0.228714,44
1,500205,Listen,2,5,NaN,-0.342249,-0.306931,44
2,500305,Listen,3,5,NaN,-0.016221,-0.217010,44
3,500405,Listen,4,5,NaN,-0.116089,-0.242624,44
4,500505,Listen,5,5,NaN,-0.242637,-0.272226,44
...,...,...,...,...,...,...,...,...
1453,500105,Listen,1,5,NaN,-0.007494,-0.187787,44
1454,500205,Listen,2,5,NaN,-0.098739,-0.291931,44
1455,500305,Listen,3,5,NaN,-0.534422,-0.210410,44
1456,500405,Listen,4,5,NaN,-0.002209,-0.195490,44
1457,500505,Listen,5,5,NaN,-0.180562,-0.174776,44

Processing epoch and power for participant 45
Processing epoch for participant 45
Read file data/ica-excluded-eeg/sub-045-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 45

Below is dataframe for participant 45

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.282628,-0.280641,45
1,500205,Listen,2,5,NaN,-0.164332,-0.205620,45
2,500305,Listen,3,5,NaN,-0.229526,-0.232126,45
3,500405,Listen,4,5,NaN,-0.328130,-0.236834,45
4,500505,Listen,5,5,NaN,-0.247732,-0.200465,45
...,...,...,...,...,...,...,...,...
1453,500913,Listen,9,13,NaN,-0.444295,-0.133155,45
1454,501013,Listen,10,13,NaN,-0.284280,-0.244275,45
1455,501113,Listen,11,13,NaN,-0.279015,-0.284392,45
1456,501213,Listen,12,13,NaN,-0.050889,-0.218429,45
1457,501313,Listen,13,13,NaN,-0.102635,-0.188860,45

Processing epoch and power for participant 46
Processing epoch for participant 46
Read file data/ica-excluded-eeg/sub-046-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 46

Below is dataframe for participant 46

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.153675,-0.254919,46
1,500205,Listen,2,5,NaN,-0.063925,-0.238524,46
2,500305,Listen,3,5,NaN,-0.261799,-0.233433,46
3,500405,Listen,4,5,NaN,-0.200187,-0.209548,46
4,500505,Listen,5,5,NaN,-0.148536,-0.222982,46
...,...,...,...,...,...,...,...,...
1453,500105,Listen,1,5,NaN,-0.191580,-0.203399,46
1454,500205,Listen,2,5,NaN,-0.127121,-0.221341,46
1455,500305,Listen,3,5,NaN,-0.439913,-0.172983,46
1456,500405,Listen,4,5,NaN,-0.073836,-0.247007,46
1457,500505,Listen,5,5,NaN,-0.169581,-0.264276,46

Processing epoch and power for participant 47
Processing epoch for participant 47
Read file data/ica-excluded-eeg/sub-047-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 47

Below is dataframe for participant 47

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.172952,-0.273314,47
1,500205,Listen,2,5,NaN,-0.109541,-0.205347,47
2,500305,Listen,3,5,NaN,-0.193502,-0.167092,47
3,500405,Listen,4,5,NaN,-0.032049,-0.279014,47
4,500505,Listen,5,5,NaN,-0.149210,-0.219026,47
...,...,...,...,...,...,...,...,...
1453,500913,Listen,9,13,NaN,0.102044,-0.014761,47
1454,501013,Listen,10,13,NaN,-0.083297,-0.509894,47
1455,501113,Listen,11,13,NaN,-0.193662,-0.285314,47
1456,501213,Listen,12,13,NaN,-0.563866,-0.290266,47
1457,501313,Listen,13,13,NaN,-0.690237,-0.365425,47

Processing epoch and power for participant 48
Processing epoch for participant 48
Read file data/ica-excluded-eeg/sub-048-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 48

Below is dataframe for participant 48

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.253232,-0.190383,48
1,500205,Listen,2,5,NaN,0.131491,-0.228370,48
2,500305,Listen,3,5,NaN,-0.399994,-0.195035,48
3,500405,Listen,4,5,NaN,-0.551076,-0.228026,48
4,500505,Listen,5,5,NaN,-0.093176,-0.185687,48
...,...,...,...,...,...,...,...,...
1453,500105,Listen,1,5,NaN,0.049141,-0.209498,48
1454,500205,Listen,2,5,NaN,-0.333324,-0.139783,48
1455,500305,Listen,3,5,NaN,-0.292188,-0.357802,48
1456,500405,Listen,4,5,NaN,-0.192672,-0.238126,48
1457,500505,Listen,5,5,NaN,-0.296509,-0.200608,48

Processing epoch and power for participant 49
Processing epoch for participant 49
Read file data/ica-excluded-eeg/sub-049-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 49

Below is dataframe for participant 49

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.360837,-0.252944,49
1,500205,Listen,2,5,NaN,-0.255335,-0.196119,49
2,500305,Listen,3,5,NaN,-0.070309,-0.273280,49
3,500405,Listen,4,5,NaN,-0.162430,-0.235387,49
4,500505,Listen,5,5,NaN,-0.057582,-0.203485,49
...,...,...,...,...,...,...,...,...
1453,500105,Listen,1,5,NaN,-0.508013,-0.298905,49
1454,500205,Listen,2,5,NaN,-0.153844,-0.195573,49
1455,500305,Listen,3,5,NaN,-0.416015,-0.098159,49
1456,500405,Listen,4,5,NaN,-0.165703,0.245485,49
1457,500505,Listen,5,5,NaN,-0.091951,0.016693,49

Processing epoch and power for participant 50
Processing epoch for participant 50
Read file data/ica-excluded-eeg/sub-050-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 50

Below is dataframe for participant 50

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500109,Listen,1,9,NaN,-0.091473,-0.215759,50
1,500209,Listen,2,9,NaN,-0.351930,-0.249833,50
2,500309,Listen,3,9,NaN,-0.186078,-0.240023,50
3,500409,Listen,4,9,NaN,-0.203990,-0.211003,50
4,500509,Listen,5,9,NaN,-0.124198,-0.229465,50
...,...,...,...,...,...,...,...,...
1453,500913,Listen,9,13,NaN,-0.306355,-0.168170,50
1454,501013,Listen,10,13,NaN,-0.511076,-0.196012,50
1455,501113,Listen,11,13,NaN,0.098277,-0.304400,50
1456,501213,Listen,12,13,NaN,-0.369719,-0.263173,50
1457,501313,Listen,13,13,NaN,-0.175977,-0.212733,50

Processing epoch and power for participant 51
Processing epoch for participant 51
Read file data/ica-excluded-eeg/sub-051-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 51

Below is dataframe for participant 51

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.175000,-0.252371,51
1,500205,Listen,2,5,NaN,-0.105475,-0.243850,51
2,500305,Listen,3,5,NaN,-0.230754,-0.195782,51
3,500405,Listen,4,5,NaN,0.037294,-0.268164,51
4,500505,Listen,5,5,NaN,-0.283062,-0.183192,51
...,...,...,...,...,...,...,...,...
1453,500105,Listen,1,5,NaN,-0.003005,-0.242595,51
1454,500205,Listen,2,5,NaN,-0.179809,-0.247262,51
1455,500305,Listen,3,5,NaN,-0.518709,-0.304378,51
1456,500405,Listen,4,5,NaN,-0.136182,-0.224124,51
1457,500505,Listen,5,5,NaN,0.021603,-0.192531,51

Processing epoch and power for participant 52
Processing epoch for participant 52
Read file data/ica-excluded-eeg/sub-052-task-eeg_ica-cleaned.fif
Skipping this label: label boundary is invalid.
Skipping this label: label boundary is invalid.
Start computing power for participant 52

Below is dataframe for participant 52

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500105,Listen,1,5,NaN,-0.162042,-0.268343,52
1,500205,Listen,2,5,NaN,-0.321358,-0.244120,52
2,500305,Listen,3,5,NaN,-0.106582,-0.188088,52
3,500405,Listen,4,5,NaN,-0.268876,-0.251257,52
4,500505,Listen,5,5,NaN,-0.141298,-0.222561,52
...,...,...,...,...,...,...,...,...
1453,500913,Listen,9,13,NaN,-0.113997,-0.176047,52
1454,501013,Listen,10,13,NaN,-0.120848,-0.268978,52
1455,501113,Listen,11,13,NaN,-0.434566,-0.307241,52
1456,501213,Listen,12,13,NaN,-0.159789,-0.207058,52
1457,501313,Listen,13,13,NaN,-0.198035,-0.235484,52

[]

In [12]:
print(f"all_participants shape is {len(all_participants)}")
display(all_participants[0])
print(f"all_participants_df shape os {all_participants_df.shape}")
all_participants_df.to_csv("eeg-power-features.csv", index=False)

all_participants shape is 20

,label,condition,position,load,correct,alpha_power,gamma_power,participant
0,500113,Listen,1,13,NaN,-0.057477,-0.192534,32
1,500213,Listen,2,13,NaN,-0.394398,-0.184071,32
2,500313,Listen,3,13,NaN,-0.412928,-0.205873,32
3,500413,Listen,4,13,NaN,-0.067001,-0.229368,32
4,500513,Listen,5,13,NaN,-0.253803,-0.232337,32
...,...,...,...,...,...,...,...,...
1453,500509,Listen,5,9,NaN,-0.036467,-0.180683,32
1454,500609,Listen,6,9,NaN,-0.180830,-0.229368,32
1455,500709,Listen,7,9,NaN,-0.352032,-0.221582,32
1456,500809,Listen,8,9,NaN,-0.604756,-0.264687,32
1457,500909,Listen,9,9,NaN,-0.057744,-0.237288,32

all_participants_df shape os (29187, 8)

#### Test cases

In [ ]:
## Test the parse function : IT WORKS! :)
# labels = ["x500813", "x500913", "x501013", "x501113", "x501213", "x501313", "x6001050", "x6001051", "x6002050", "x6002051", "x6003050", "x6003051", "x6004050", "x6004051", "x6005050", "x6005051", "x6001090", "x6001091", "x6002090"]
# for label in labels:
#    print(parse_label(label))

## Testing `mne.events_from_annotations`
# test_raw = mne.io.read_raw_fif("data/ica-excluded-eeg/sub-051-task-eeg_ica-cleaned.fif", preload=True)
# events, event_id = mne.events_from_annotations(test_raw)
# print(f"Events : {events}")
# print(f"Event ID: {event_id}")

      "x500813": "control 08/13: listen to digit 8 in 13 digit sequence",
      "x500913": "control 09/13: listen to digit 9 in 13 digit sequence",
      "x501013": "control 10/13: listen to digit 10 in 13 digit sequence",
      "x501113": "control 11/13: listen to digit 11 in 13 digit sequence",
      "x501113": "control 12/13: listen to digit 12 in 13 digit sequence",
      "x501313": "control 13/13: listen to digit 13 (last) in 13 digit sequence",
      "x6001050": "memory 01/05 error: memorize digit 1 (first) in 5 digit sequence; forgotten",
      "x6001051": "memory 01/05 correct: memorize digit 1 (first) in 5 digit sequence; correctly recalled",
      "x6002050": "memory 02/05 error: memorize digit 2 in 5 digit sequence; forgotten",
      "x6002051": "memory 02/05 correct: memorize digit 2 in 5 digit sequence; correctly recalled",
      "x6003050": "memory 03/05 error: memorize digit 3 in 5 digit sequence; forgotten",
      "x6003051": "memory 03/05 correct: memorize digit 3 in 5 digit sequence; correctly recalled",
      "x6004050": "memory 04/05 error: memorize digit 4 in 5 digit sequence; forgotten",
      "x6004051": "memory 04/05 correct: memorize digit 4 in 5 digit sequence; correctly recalled",
      "x6005050": "memory 05/05 error: memorize digit 5 (last) in 5 digit sequence; forgotten",
      "x6005051": "memory 05/05 correct: memorize digit 5 (last) in 5 digit sequence; correctly recalled",
      "x6001090": "memory 01/09 error: memorize digit 1 (first) in 9 digit sequence; forgotten",
      "x6001091": "memory 01/09 correct: memorize digit 1 (first) in 9 digit sequence; correctly recalled",
      "x6002090": "memory 02/09 error: memorize digit 2 in 9 digi

## Next steps
- Rebalance the dataset to include participants from `listen` group
- Analyse scores to see min-max of performance in memory task
- Create correlation matrix of EEG/ECG and memory performance
- Create clusters of cognitive load and memory performance
- I have a few questions on how best to approach, will need to talk to Mehdi and Dr. Karduni